

CC:clang++

CFLAGS:-O2 -Wall -Wextra

cube: cube.cpp
	clang++ -O2 -Wall -Wextra cube.cpp -o main.o

constructor: constructor.cpp
	clang++ -O2 -Wall -Wextra constructor.cpp -o main.o && ./main.o

clean:
	rm *.o
